/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

type UpdateTargetDto struct {
	// Audience object describing target segmentation.
	Audience *AllOfUpdateTargetDtoAudience `json:"audience"`
	// Target name
	Name string `json:"name,omitempty"`
	// Rollout sub-document describing how a Target's audience is rolled out
	Rollout *AllOfUpdateTargetDtoRollout `json:"rollout,omitempty"`
	// Specifies variation distribution percentages for features
	Distribution []TargetDistribution `json:"distribution"`
}
