/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

type UpdateEnvironmentDto struct {
	// A unique display name
	Name string `json:"name,omitempty"`
	// Unique Environment identifier, can be used in the SDK / API to reference by key rather than ID. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key,omitempty"`
	// Environment description.
	Description string `json:"description,omitempty"`
	// Environment display color, used to highlight different environments on the dashboard. Must use Hex color code.
	Color string `json:"color,omitempty"`
	// The environment type
	Type_ string `json:"type,omitempty"`
	// Environment based settings
	Settings *AllOfUpdateEnvironmentDtoSettings `json:"settings,omitempty"`
}
