/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

type UserCustomFilter struct {
	// Comparator to use
	Comparator string `json:"comparator"`
	// Data Key used for custom data
	DataKey string `json:"dataKey"`
	// Data Key Type used for custom data
	DataKeyType string `json:"dataKeyType"`
	// An array of values is required for all filters except when the comparator is 'exist' or '!exist'
	Values *interface{} `json:"values,omitempty"`
	// Filter type of this audience
	Type_ string `json:"type"`
	// Sub type of this filter
	SubType string `json:"subType"`
}
