/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

// Audience filters, describing logic for segmenting users
type AllOfTargetAudienceFilters struct {
	// Filters to apply using the \"operator\" operation
	Filters []interface{} `json:"filters"`
	// Operator type if this object represents an operator, and not a filter
	Operator string `json:"operator"`
}
