/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

// SDK Keys for mobile SDKs / client SDKs / server SDKs. Multiple keys can be created to allow for key rotation.
type AllOfEnvironmentSdkKeys struct {
	Mobile []ApiKey `json:"mobile"`
	Client []ApiKey `json:"client"`
	Server []ApiKey `json:"server"`
}
