/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

import (
	"time"
)

// Rollout sub-document describing how a Target's audience is rolled out
type AllOfUpdateTargetDtoRollout struct {
	// Rollout start percentage
	StartPercentage float64 `json:"startPercentage,omitempty"`
	// Type of rollout
	Type_ interface{} `json:"type"`
	// Date to start rollout
	StartDate time.Time `json:"startDate"`
	// Stages of rollout
	Stages []RolloutStage `json:"stages,omitempty"`
}
