/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type FeatureDataPoint struct {
	// Date of this data point
	Date time.Time `json:"date"`
	// Mapping of evaluation variation (variation1, variation2 etc.) to number of evaluations in that variation
	Values *interface{} `json:"values"`
}
