/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type ProjectDataPoint struct {
	// Date of this datapoint
	Date time.Time `json:"date"`
	// Number of variable evaluations across the whole project for this data point, grouped by user
	Value float64 `json:"value"`
}
