/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type RolloutStage struct {
	// Target percentage to reach by the step date
	Percentage float64 `json:"percentage"`
	// Defines the transition into this percentage level
	Type_ *interface{} `json:"type"`
	// Date the target percentage should be fully applied
	Date time.Time `json:"date"`
}
