/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type FeatureConfig struct {
	// ID of the Feature owning the Configuration
	Feature string `json:"_feature"`
	// ID of the Environment owning the Configuration
	Environment string `json:"_environment"`
	// User who created the Feature Configuration
	CreatedBy string `json:"_createdBy"`
	// Status of the Feature Configuration
	Status string `json:"status"`
	// Date the Feature Configuration was started
	StartedAt time.Time `json:"startedAt,omitempty"`
	// The date the Feature Configuration was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// The targets to evaluate what variation a user should be delivered
	Targets []Target `json:"targets"`
}
