/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

type TargetDistribution struct {
	// Distribution percentage for the variation
	Percentage float64 `json:"percentage"`
	// Variation ID or key from `feature.variations`
	Variation string `json:"_variation"`
}
