/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

type CreateCustomPropertyDto struct {
	// Display name for Custom Property.
	Name string `json:"name"`
	// Auto generated key to be used by the API to reference by 'key' rather then _id for CRUD operations. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key"`
	// Type of the Custom Propety. Must be one of: \"Boolean\", \"Number\", \"Semver\" or \"String\"
	Type_ string `json:"type"`
	// Custom Property key, must be unique by Project. Only to be used by the SDKs to reference the Custom Property..
	PropertyKey string `json:"propertyKey"`
}
