/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

// Environment based settings
type AllOfUpdateEnvironmentDtoSettings struct {
	// A unique App Icon URI for a given environment
	AppIconURI string `json:"appIconURI,omitempty"`
}
