/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type Project struct {
	// Project name
	Name string `json:"name"`
	// A unique key to identify the Project
	Key string `json:"key"`
	// A description of the Project
	Description string `json:"description,omitempty"`
	// A unique Project ID
	Id string `json:"_id"`
	// ID of the Organization owning the Project
	Organization string `json:"_organization"`
	// ID of the User who created the project
	CreatedBy string `json:"_createdBy"`
	// The date the Project was created
	CreatedAt time.Time `json:"createdAt"`
	// The date the Project was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}
