/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk

type CreateFeatureDto struct {
	// Name of the Feature
	Name string `json:"name"`
	// Unique key by Project, can be used in the SDK / API to reference by 'key' rather than _id. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key"`
	// Feature description.
	Description string `json:"description,omitempty"`
	// Variation configurations to be used by feature configurations.
	Variations []FeatureVariationDto `json:"variations,omitempty"`
	// Variable definitions to be referenced in variations
	Variables []CreateVariableDto `json:"variables,omitempty"`
	// The Feature type
	Type_ string `json:"type,omitempty"`
	// Tags to organize Features on the dashboard
	Tags []string `json:"tags,omitempty"`
}
