/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type ApiKey struct {
	// A unique API key
	Key string `json:"key"`
	// Date the key was generated
	CreatedAt time.Time `json:"createdAt"`
}
