/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type Variable struct {
	// Variable name
	Name string `json:"name,omitempty"`
	// A description of the Variable
	Description string `json:"description,omitempty"`
	// Unique Variable identifier, can be used in the SDK / API to reference by key rather then ID. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key"`
	// A unique Variable ID
	Id string `json:"_id"`
	// The ID of the Project this Variable belongs to
	Project string `json:"_project"`
	// The ID of the Feature this Variable belongs to
	Feature string `json:"_feature,omitempty"`
	// The type of Variable. Must be one of [String | Boolean | Number | JSON]
	Type_ string `json:"type"`
	// A default value for the Variable
	DefaultValue *interface{} `json:"defaultValue,omitempty"`
	// The system that was used for the creation of the Variable.
	Source string `json:"source"`
	// ID of the User who created the Variable.
	CreatedBy string `json:"_createdBy,omitempty"`
	// The date the Variable was created
	CreatedAt time.Time `json:"createdAt"`
	// The date the Variable was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}
