/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type CustomProperty struct {
	// Display name for Custom Property.
	Name string `json:"name"`
	// Auto generated key to be used by the API to reference by 'key' rather then _id for CRUD operations. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key"`
	// A unique CustomProperty ID
	Id string `json:"_id"`
	// The Project owning the Custom Property
	Project string `json:"_project"`
	// ID of the User who created the project
	CreatedBy string `json:"_createdBy"`
	// Custom Property key, must be unique by Project. Only to be used by the SDKs to reference the Custom Property..
	PropertyKey string `json:"propertyKey"`
	// The Custom Property type
	Type_ string `json:"type"`
	// The date the Project was created
	CreatedAt time.Time `json:"createdAt"`
	// The date the Project was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}
