/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type Environment struct {
	// A unique display name
	Name string `json:"name"`
	// Unique Environment identifier, can be used in the SDK / API to reference by key rather than ID. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key"`
	// Environment description.
	Description string `json:"description,omitempty"`
	// Environment display color, used to highlight different environments on the dashboard. Must use Hex color code.
	Color string `json:"color,omitempty"`
	// A unique Environment ID
	Id string `json:"_id"`
	// The Project owning the Environment
	Project string `json:"_project"`
	// The environment type
	Type_ string `json:"type"`
	// ID of the User who created the Environment.
	CreatedBy string `json:"_createdBy"`
	// The date the Environment was created
	CreatedAt time.Time `json:"createdAt"`
	// The date the Environment was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// SDK Keys for mobile SDKs / client SDKs / server SDKs. Multiple keys can be created to allow for key rotation.
	SdkKeys *AllOfEnvironmentSdkKeys `json:"sdkKeys"`
	// Environment based settings
	Settings *AllOfEnvironmentSettings `json:"settings,omitempty"`
}
