/*
 * DevCycle Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go_mgmt_sdk
import (
	"time"
)

type Feature struct {
	// Name of the Feature
	Name string `json:"name"`
	// Unique key by Project, can be used in the SDK / API to reference by 'key' rather than _id. Must only contain lower-case characters and `_` or `-`.
	Key string `json:"key"`
	// Feature description.
	Description string `json:"description,omitempty"`
	// A unique Feature ID
	Id string `json:"_id"`
	// The Project owning the Feature
	Project string `json:"_project"`
	// Source that created the Feature
	Source string `json:"source"`
	// The Feature type
	Type_ string `json:"type,omitempty"`
	// ID of the User who created the Feature
	CreatedBy string `json:"_createdBy,omitempty"`
	// The date the Feature was created
	CreatedAt time.Time `json:"createdAt"`
	// The date the Feature was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Variation configurations to be used by feature configurations.
	Variations []Variation `json:"variations,omitempty"`
	// Variable definitions to be referenced in variations
	Variables []Variable `json:"variables,omitempty"`
	// Tags to organize Features on the dashboard
	Tags []string `json:"tags,omitempty"`
}
